<a href="https://colab.research.google.com/github/caraujom/Labs_IH/blob/main/class_activities_1_08cra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
data=pd.read_csv('regression_data.txt')

In [5]:
data

AVGGIFT   HV1_log  IC1_transformed  IC5_transformed  gender  TARGET_D
0     15.500000  7.760467        17.343389         4.181353    Male      21.0
1      3.080000  6.208590        16.230984         4.150313    Male       3.0
2      7.500000  7.113956        18.047227         4.205057  Female      20.0
3      6.700000  5.783825        11.737110         4.055333    Male       5.0
4      8.785714  6.643790        12.494862         4.088969  Female      10.0
...         ...       ...              ...              ...     ...       ...
4665  15.500000  6.552508        15.280561         4.187901    Male      25.0
4666  11.857143  8.118803        15.029617         4.248632    Male      19.0
4667  11.333333  6.551080        15.742430         4.179506  Female      10.0
4668  13.000000  6.398595        13.326031         4.124159    Male      25.0
4669  17.923077  6.823286        17.417748         4.256304    Male      25.0

[4670 rows x 6 columns]

In [7]:
data.dtypes

AVGGIFT            float64
HV1_log            float64
IC1_transformed    float64
IC5_transformed    float64
gender              object
TARGET_D           float64
dtype: object

In [8]:
data['gender'].unique()


array(['Male', 'Female', 'U'], dtype=object)

In [9]:
from sklearn.preprocessing import OneHotEncoder
#pasa de categorias a columnas 

In [11]:
X_cat= data.select_dtypes(include='object')
X_cat

gender
0       Male
1       Male
2     Female
3       Male
4     Female
...      ...
4665    Male
4666    Male
4667  Female
4668    Male
4669    Male

[4670 rows x 1 columns]

In [12]:
X_cat.isna().sum()

gender    0
dtype: int64

In [13]:
encoder=OneHotEncoder().fit(X_cat)
encoded=encoder.transform(X_cat)
encoded

<4670x3 sparse matrix of type '<class 'numpy.float64'>'
	with 4670 stored elements in Compressed Sparse Row format>

In [14]:
encoder=OneHotEncoder().fit(X_cat)
encoded=encoder.transform(X_cat).toarray() #lo da como arreglo de numpy
encoded

array([[0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [ ]:
#siempre buscamos evitar correlacion entre las columnas (evita dependencias entre ellas)
#por eso encontraremos que se elimina alguna columna del array del onehotencoder


In [17]:
#otra forma de hacerlo
X_cat=data.select_dtypes(include='object')
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder().fit(X_cat).transform(X_cat)
le

array([1, 1, 0, ..., 0, 1, 1])

In [19]:
np.unique(le)

array([0, 1, 2])

In [21]:
# retomando numericos de ayer
from sklearn.preprocessing import StandardScaler
X_num=data.drop(['TARGET_D','gender'],axis=1)

transformer=StandardScaler().fit(X_num)
x_ss=transformer.transform(X_num)

X=np.concatenate((x_ss,encoded),axis=1)

In [22]:
X

array([[ 0.37582816,  1.55744187,  0.74494534, ...,  0.        ,
         1.        ,  0.        ],
       [-0.85426035, -0.83191217,  0.24813711, ...,  0.        ,
         1.        ,  0.        ],
       [-0.41649938,  0.56203858,  1.05928459, ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [-0.03684243, -0.3045955 ,  0.02994518, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.1282258 , -0.5393703 , -1.0492367 , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.61581198,  0.1145073 ,  0.77815463, ...,  0.        ,
         1.        ,  0.        ]])

In [ ]:
#medidas para ver que tan bueno es un modelo 

In [ ]:
from sklearn.metrics 

In [23]:
'''Diferencias entre regresión y clasificación en aprendizaje automático'''


'Diferencias entre regresión y clasificación en aprendizaje automático'

Los problemas de regresión se utilizan cuando se desea distinguir entre puntos individuales. Por ejemplo, predecir los niveles de ciertos contaminantes ene aire en base a datos como la temperatura y humedad. En cambio, los problemas de clasificación se han de utilizar cuando se desea diferencia entre clases de puntos que corresponden a categorías. Por ejemplo, cuando se desea conocer si un cliente es hombre o mujer en base al contenido de su cesta de la compra.

